### ISSUE TITLE
Generated template needs additional files

### ISSUE THREAD

**Issue by denialhaag** [Munich-Quantum-Software-Stack/QDMI#91] opened 2024-11-08 16:09 UTC
I wanted to report a few issues I ran into when working with the generated device template.

One currently has to manually add a number of additional files for the project to compile:

- `cmake/PrefixHandling.cmake`
- `cmake/prefix_defs.txt`
- `include/qdmi/device.h` and its dependencies

Futhermore, one has to edit the root `CMakeLists.txt` to add the following lines:

```
# set some important directories
set(QDMI_INCLUDE_BUILD_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/include"
    CACHE INTERNAL "Include directory")
set(QDMI_TEST_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/test"
    CACHE INTERNAL "Test directory")
set(QDMI_CMAKE_DIR
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake"
    CACHE INTERNAL "CMake directory")
```

**Comment by ystade** [comment] 2024-11-08 16:44
Thanks you @denialhaag for bringingin up this issue. Unfortunately, I cannot reproduce the problem on my machine.

We just merged a new PR #90 that add an extensive explanation of the usage of the [templates](https://munich-quantum-software-stack.github.io/QDMI/md_docs_2templates.html) Could you please read thorugh those steps and check whether they resolve your problem. If the problem persists, could you please detail the steps until you encountered the issue such that it is easier for us to figure out what happened there? 

Thank you so much for your collaboration!

**Comment by denialhaag** [comment] 2024-11-08 17:32
My bad, I pulled `QDMI`, cretaed a new template, and it worked like a charm. Maybe it was related to the pinned revision. 🤔

**Comment by burgholzer** [comment] 2024-11-08 17:53
> My bad, I pulled `QDMI`, cretaed a new template, and it worked like a charm. Maybe it was related to the pinned revision. 🤔 

That could very much be it.
We adjusted that part in the latest PR.
Going to close this for now. Feel free to reopen if any problems still arise.

**Closed as completed by burgholzer** 2024-11-08 17:53 UTC
Labels: bug, usability
